export const LOGIN_USER = "LOGIN_USER";
export const RTEGISTER_USER = "RTEGISTER_USER";
export const LOAD_USER = "LOAD_USER";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const LOG_OUT = "LOG_OUT";
export const VARIFY_USER = "VARIFY_USER";
export const SEND_MAIL = "SEND_MAIL";
export const CLEAR = "CLEAR";
export const LOG_IN_FAIL = 'LOG_IN_FAIL'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG'
export const VARIFY_USER_FAIL = "VARIFY_USER_FAIL";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL'
export const UPDATE_EMAIL_FAIL= 'UPDATE_EMAIL_FAIL'
export const ERROR_CLEAR= 'ERROR_CLEAR'
export const LOAD_ERROR = 'LOAD_ERROR'
/*Aauthed Profiles Part */
export const ADD_PROFILE = "ADD_PROFILE";
export const LOAD_PROFILE = "LOAD_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CREATE_POST = "CREATE_POST";
export const LOAD_POST = "LOAD_POST";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPLOADING = "UPLOADING";
export const LOADING = "LOADING";
export const UPDATE_COVER_IMG = "UPDATE_COVER_IMG";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL' 
export const UPDATE_PROFILE_FAIL= 'UPDATE_PROFILE_FAIL' 
export const CREATE_POST_FAIL= 'CREATE_POST_FAIL'  
export const UPDATE_COVER_IMG_FAIL= 'UPDATE_COVER_IMG_FAIL' 
export const GET_USER_FAIL = 'GET_USER_FAIL'
export const LOAD_POST_FAIL = "LOAD_POST_FAIL"
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
/* General Profile Part */
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER = "GET_USER";
export const DELETE_USER_PROFILE = "DELETE_USER_PROFILE";
export const IS_LOADING = "IS_LOADING";
export const DELETE_SEARCH = "DELETE_SEARCH";
export const GET_USER_POST = "GET_USER_POST";
export const GET_SEARCH = "GET_SEARCH";
export const NO_MORE_LOAD = "NO_MORE_LOAD";
export const NO_POST_LOAD = 'NO_POST_LOAD'
export const CLEAR_NO_MORE_LOAD = 'CLEAR_NO_MORE_LOAD'
/*export const = '' 
export const = '' 
export const = '' 
export const = ''  */
